[tool.poetry]
name = "synergy"
version = "0.1.0"
description = ""
authors = ["sindlinger <candeia.goncalves@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
cmake = "^3.30.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
